# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res_rc


class Ui_LiteEncoding(object):
    def setupUi(self, LiteEncoding):
        LiteEncoding.setObjectName("LiteEncoding")
        LiteEncoding.setWindowModality(QtCore.Qt.NonModal)
        LiteEncoding.setEnabled(True)
        LiteEncoding.resize(949, 599)
        LiteEncoding.setStyleSheet("font: 75 12pt \"Comic Sans MS\";")
        self.centralwidget = QtWidgets.QWidget(LiteEncoding)
        self.centralwidget.setObjectName("centralwidget")
        self.ProgramName = QtWidgets.QLabel(self.centralwidget)
        self.ProgramName.setGeometry(QtCore.QRect(10, 10, 251, 61))
        self.ProgramName.setStyleSheet("QLabel {\n"
"background-color: rgba(0, 0, 0, 150);\n"
"color: rgb(255, 139, 160);\n"
"font: 75 italic 26pt \"Comic Sans MS\";\n"
"border-radius: 11px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"}")
        self.ProgramName.setObjectName("ProgramName")
        self.bg = QtWidgets.QLabel(self.centralwidget)
        self.bg.setGeometry(QtCore.QRect(0, 0, 951, 601))
        self.bg.setStyleSheet("background-image: url(:/bg/bg.jpg);")
        self.bg.setObjectName("bg")
        self.Btns_List = QtWidgets.QFrame(self.centralwidget)
        self.Btns_List.setGeometry(QtCore.QRect(10, 80, 511, 501))
        self.Btns_List.setStyleSheet("QFrame#Btns_List {\n"
"background-color: rgba(0, 0, 0, 90);\n"
"border-radius: 12px;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"}\n"
"")
        self.Btns_List.setObjectName("Btns_List")
        self.Btns = QtWidgets.QHBoxLayout(self.Btns_List)
        self.Btns.setObjectName("Btns")
        self.Encode_Btns = QtWidgets.QFrame(self.Btns_List)
        self.Encode_Btns.setObjectName("Encode_Btns")
        self.Encode = QtWidgets.QVBoxLayout(self.Encode_Btns)
        self.Encode.setObjectName("Encode")
        self.EncodeASCII16 = QtWidgets.QPushButton(self.Encode_Btns)
        self.EncodeASCII16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EncodeASCII16.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 139, 160, 80);    \n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 139, 160, 120);    \n"
"}")
        self.EncodeASCII16.setObjectName("EncodeASCII16")
        self.Encode.addWidget(self.EncodeASCII16)
        self.EncodeASCII10 = QtWidgets.QPushButton(self.Encode_Btns)
        self.EncodeASCII10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EncodeASCII10.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 139, 160, 80);    \n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 139, 160, 120);    \n"
"}")
        self.EncodeASCII10.setObjectName("EncodeASCII10")
        self.Encode.addWidget(self.EncodeASCII10)
        self.EncodeASCII2 = QtWidgets.QPushButton(self.Encode_Btns)
        self.EncodeASCII2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EncodeASCII2.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 139, 160, 80);    \n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 139, 160, 120);    \n"
"}")
        self.EncodeASCII2.setObjectName("EncodeASCII2")
        self.Encode.addWidget(self.EncodeASCII2)
        self.EncodeBASE64 = QtWidgets.QPushButton(self.Encode_Btns)
        self.EncodeBASE64.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.EncodeBASE64.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 139, 160, 80);    \n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 139, 160, 120);    \n"
"}")
        self.EncodeBASE64.setObjectName("EncodeBASE64")
        self.Encode.addWidget(self.EncodeBASE64)
        self.Btns.addWidget(self.Encode_Btns)
        self.Decode_Btns = QtWidgets.QFrame(self.Btns_List)
        self.Decode_Btns.setStyleSheet("")
        self.Decode_Btns.setObjectName("Decode_Btns")
        self.Decode = QtWidgets.QVBoxLayout(self.Decode_Btns)
        self.Decode.setObjectName("Decode")
        self.DecodeASCII16 = QtWidgets.QPushButton(self.Decode_Btns)
        self.DecodeASCII16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DecodeASCII16.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 139, 160, 80);    \n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 139, 160, 120);    \n"
"}")
        self.DecodeASCII16.setObjectName("DecodeASCII16")
        self.Decode.addWidget(self.DecodeASCII16)
        self.DecodeASCII10 = QtWidgets.QPushButton(self.Decode_Btns)
        self.DecodeASCII10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DecodeASCII10.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 139, 160, 80);    \n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 139, 160, 120);    \n"
"}")
        self.DecodeASCII10.setObjectName("DecodeASCII10")
        self.Decode.addWidget(self.DecodeASCII10)
        self.DecodeASCII2 = QtWidgets.QPushButton(self.Decode_Btns)
        self.DecodeASCII2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DecodeASCII2.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 139, 160, 80);    \n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 139, 160, 120);    \n"
"}")
        self.DecodeASCII2.setObjectName("DecodeASCII2")
        self.Decode.addWidget(self.DecodeASCII2)
        self.DecodeBASE64 = QtWidgets.QPushButton(self.Decode_Btns)
        self.DecodeBASE64.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.DecodeBASE64.setStyleSheet("QPushButton {\n"
"background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(255, 139, 160, 80);    \n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(255, 139, 160, 120);    \n"
"}")
        self.DecodeBASE64.setObjectName("DecodeBASE64")
        self.Decode.addWidget(self.DecodeBASE64)
        self.Btns.addWidget(self.Decode_Btns)
        self.Input = QtWidgets.QFrame(self.centralwidget)
        self.Input.setGeometry(QtCore.QRect(520, 80, 421, 251))
        self.Input.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;")
        self.Input.setObjectName("Input")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Input)
        self.verticalLayout.setObjectName("verticalLayout")
        self.InputLabel = QtWidgets.QLabel(self.Input)
        self.InputLabel.setStyleSheet("QLabel {\n"
"background-color: rgba(0, 0, 0, 150);\n"
"color: rgb(255, 139, 160);\n"
"font: 75 italic 26pt \"Comic Sans MS\";\n"
"border-radius: 11px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"}")
        self.InputLabel.setObjectName("InputLabel")
        self.verticalLayout.addWidget(self.InputLabel)
        self.InputText = QtWidgets.QPlainTextEdit(self.Input)
        self.InputText.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;\n"
"")
        self.InputText.setObjectName("InputText")
        self.verticalLayout.addWidget(self.InputText)
        self.Output = QtWidgets.QFrame(self.centralwidget)
        self.Output.setGeometry(QtCore.QRect(520, 330, 421, 251))
        self.Output.setStyleSheet("background-color: rgba(0, 0, 0, 80);\n"
"color: white;\n"
"border: 2px solid rgb(255, 139, 160);\n"
"border-radius: 7px;")
        self.Output.setObjectName("Output")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Output)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.OutputLabel = QtWidgets.QLabel(self.Output)
        self.OutputLabel.setMouseTracking(False)
        self.OutputLabel.setTabletTracking(False)
        self.OutputLabel.setAcceptDrops(True)
        self.OutputLabel.setStyleSheet("QLabel {\n"
"background-color: rgba(0, 0, 0, 150);\n"
"color: rgb(255, 139, 160);\n"
"font: 75 italic 26pt \"Comic Sans MS\";\n"
"border-radius: 11px;\n"
"padding-left: 10px;\n"
"padding-right: 10px;\n"
"}")
        self.OutputLabel.setObjectName("OutputLabel")
        self.verticalLayout_2.addWidget(self.OutputLabel)
        self.OutputText = QtWidgets.QTextBrowser(self.Output)
        self.OutputText.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.OutputText.setMouseTracking(True)
        self.OutputText.setTabletTracking(True)
        self.OutputText.setAcceptDrops(False)
        self.OutputText.setObjectName("OutputText")
        self.verticalLayout_2.addWidget(self.OutputText)
        self.bg.raise_()
        self.ProgramName.raise_()
        self.Btns_List.raise_()
        self.Input.raise_()
        self.Output.raise_()
        LiteEncoding.setCentralWidget(self.centralwidget)

        self.retranslateUi(LiteEncoding)
        QtCore.QMetaObject.connectSlotsByName(LiteEncoding)

    def retranslateUi(self, LiteEncoding):
        _translate = QtCore.QCoreApplication.translate
        LiteEncoding.setWindowTitle(_translate("LiteEncoding", "LiteEncoding"))
        self.ProgramName.setText(_translate("LiteEncoding", "LiteEncoding"))
        self.bg.setText(_translate("LiteEncoding", "я"))
        self.EncodeASCII16.setText(_translate("LiteEncoding", "Encode ASCII (hexadecimall)"))
        self.EncodeASCII10.setText(_translate("LiteEncoding", "Encode ASCII (decimal)"))
        self.EncodeASCII2.setText(_translate("LiteEncoding", "Encode ASCII (binary)"))
        self.EncodeBASE64.setText(_translate("LiteEncoding", "Encode BASE64"))
        self.DecodeASCII16.setText(_translate("LiteEncoding", "Decode ASCII (hexadecimall)"))
        self.DecodeASCII10.setText(_translate("LiteEncoding", "Decode ASCII (decimal)"))
        self.DecodeASCII2.setText(_translate("LiteEncoding", "Decode ASCII (binary)"))
        self.DecodeBASE64.setText(_translate("LiteEncoding", "Decode BASE64"))
        self.InputLabel.setText(_translate("LiteEncoding", "Input"))
        self.OutputLabel.setText(_translate("LiteEncoding", "Output"))
        self.OutputText.setHtml(_translate("LiteEncoding", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Comic Sans MS\'; font-size:12pt; font-weight:72; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
